name: CI-CD Pipeline     #name of the pipeline

on:
  push:                  #runs when you push code
    branches:
      - master           #only triggers if code is pushed to master branch

jobs:
  build:                 #defines a job name build (pipeline can have multiple jobs)
    runs-on: self-hosted    #pipeline runs on your own server/machine

    steps:         #tasks  start executing one by one       
      - name: Checkout Code    #downnload github repo code into runner
        uses: actions/checkout@v3

      - name: Build Docker Image    #builds docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.run_number }} ./website
        #docker build -> create docker image      -t -> tag      ${{ secrets.DOCKER_USERNAME }} -> secure docker hub username
        #myapp -> image name     ${{ github.run_number }} -> unique version      ./website -> folder where dockerfile exists

      - name: Tag Latest Image        #creates another tag (k8s will pull the lastest)
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Login to Docker Hub        #logs into docker hub securely
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        #password comes from github secrets, avoids hardcoding the creds
        
      - name: Push Image to Docker Hub      #upload image to docker hub
        run: |                              # " | " -> runs multiple commands line by line
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Run New Container             #runs container on server
        run: docker run -d -p 8081:80 --name mycontainer vijetavernekar/myapp:latest
        # -d -> detached mode           -p 8081:80 -> browser:8080  container:80      --name my container -> container name
        # http://<server-ip>:8081
        
      - name: Scan Image with Trivy         # scans docker images for vulnerabilities 
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/myapp:latest'

      - name: Deploy to Kubernetes          #deploys app to K8s
        run: |
          kubectl apply -f k8s/deployment.yml         # deployment.yml -> creates pods
          kubectl apply -f k8s/service.yml            # service.yml -> exposes app
          
